# Generated by Django 4.2.23 on 2025-07-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Plantilla')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
            ],
            options={
                'verbose_name': 'Plantilla de Programa',
                'verbose_name_plural': 'Plantillas de Programas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.repertoirepiece', verbose_name='Pieza')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='program_templates.programtemplate')),
            ],
            options={
                'verbose_name': 'Pieza de Plantilla',
                'verbose_name_plural': 'Piezas de la Plantilla',
                'ordering': ['order'],
            },
        ),
    ]
