# Generated by Django 4.2.23 on 2025-06-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display tags.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepertoirePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la pieza musical.', max_length=200)),
                ('compositor', models.CharField(blank=True, help_text='Compositor de la obra.', max_length=150, null=True)),
                ('tonalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('letra_original', models.TextField(blank=True, null=True)),
                ('letra_traducida', models.TextField(blank=True, help_text='Traducción al español, si aplica.', null=True)),
                ('video_url', models.CharField(blank=True, help_text="URL de 'embed' de YouTube (ej. https://www.youtube.com/embed/VIDEO_ID)", max_length=255, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='repertoire_pieces', to='main.tag')),
            ],
            options={
                'verbose_name': 'Pieza de Repertorio',
                'verbose_name_plural': 'Piezas de Repertorio',
                'ordering': ['nombre'],
            },
        ),
    ]
