# Generated by Django 4.2.23 on 2025-07-03 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('quotes', '0005_quote_program_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Programa del Evento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas del Programa')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'Programa de Evento',
                'verbose_name_plural': 'Programas de Eventos',
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.repertoirepiece', verbose_name='Pieza')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='programs.program')),
            ],
            options={
                'verbose_name': 'Pieza del Programa',
                'verbose_name_plural': 'Piezas del Programa',
                'ordering': ['order'],
            },
        ),
    ]
