# Generated by Django 4.2.23 on 2025-07-03 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name'], 'verbose_name': 'Programa de Evento', 'verbose_name_plural': 'Programas de Eventos'},
        ),
        migrations.AlterField(
            model_name='programitem',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.repertoirepiece', verbose_name='Pieza'),
        ),
    ]
