# Generated by Django 4.2.23 on 2025-06-27 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Programa de Evento', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location_details', models.CharField(blank=True, max_length=300, null=True)),
                ('is_exterior', models.BooleanField(default=False)),
                ('num_voices', models.IntegerField(default=1)),
                ('num_musicians', models.IntegerField(default=1)),
                ('dress_code', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('contact_method', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('cost_musicians_base', models.FloatField(default=0)),
                ('cost_weekend_fee', models.FloatField(default=0)),
                ('cost_distance_fee', models.FloatField(default=0)),
                ('cost_gala_fee', models.FloatField(default=0)),
                ('cost_primetime_fee', models.FloatField(default=0)),
                ('cost_manager_base', models.FloatField(default=0)),
                ('cost_manager_per_person', models.FloatField(default=0)),
                ('cost_manager_exterior', models.FloatField(default=0)),
                ('cost_manager_boda', models.FloatField(default=0)),
                ('cost_car_fee', models.FloatField(default=0)),
                ('total_musician_payout_rounded', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote', to='quotes.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.program')),
                ('repertoire_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.repertoirepiece')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='pieces',
            field=models.ManyToManyField(related_name='programs', through='quotes.ProgramItem', to='main.repertoirepiece'),
        ),
    ]
