# Generated by Django 4.2.23 on 2025-06-29 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display event types.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Programa de Evento', max_length=150, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('location_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location_details', models.CharField(blank=True, max_length=300, null=True)),
                ('is_exterior', models.BooleanField(default=False)),
                ('num_voices', models.IntegerField(default=1)),
                ('num_musicians', models.IntegerField(default=1)),
                ('dress_code', models.CharField(blank=True, max_length=50, null=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('contact_method', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('cost_musicians_base', models.FloatField(default=0)),
                ('cost_weekend_fee', models.FloatField(default=0)),
                ('cost_distance_fee', models.FloatField(default=0)),
                ('cost_gala_fee', models.FloatField(default=0)),
                ('cost_primetime_fee', models.FloatField(default=0)),
                ('cost_manager_base', models.FloatField(default=0)),
                ('cost_manager_per_person', models.FloatField(default=0)),
                ('cost_manager_exterior', models.FloatField(default=0)),
                ('cost_manager_boda', models.FloatField(default=0)),
                ('cost_car_fee', models.FloatField(default=0)),
                ('total_musician_payout_rounded', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('UNCONFIRMED', 'Unconfirmed'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='UNCONFIRMED', max_length=20)),
                ('created_by_source', models.CharField(choices=[('WEBSITE', 'Website'), ('ADMIN', 'Admin')], default='WEBSITE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, help_text='User who created or last saved the quote in the admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.eventtype', verbose_name='Event Type')),
                ('program', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote', to='quotes.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.program')),
                ('repertoire_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.repertoirepiece')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='pieces',
            field=models.ManyToManyField(related_name='programs', through='quotes.ProgramItem', to='main.repertoirepiece'),
        ),
    ]
