# Generated by Django 4.2.23 on 2025-06-30 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display event types.')),
                ('is_funeral_type', models.BooleanField(default=False, help_text='Funerals always use weekday rates.')),
                ('has_wedding_fee', models.BooleanField(default=False, help_text='Adds special manager fee for weddings.')),
                ('manager_base_fee', models.FloatField(default=200.0, help_text='Base manager fee for this event.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_singers', models.PositiveIntegerField(default=1, verbose_name='Número de Voces')),
                ('num_instrument_players', models.PositiveIntegerField(default=1, verbose_name='Número de Músicos')),
                ('is_active', models.BooleanField(default=True, help_text='Show this package as an option in the quote form.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display packages on the website.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=12, unique=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('location_type', models.CharField(blank=True, choices=[('dentro_periferico', 'Dentro del periférico de Guadalajara'), ('fuera_periferico', 'Fuera del periférico (ZMG)'), ('1_hora', 'A 1 hora de Guadalajara'), ('2_horas', 'A 2 horas de Guadalajara'), ('3_horas', 'A más de 3 horas de Guadalajara')], max_length=100, null=True, verbose_name='Ubicación')),
                ('event_address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Dirección del Evento')),
                ('is_exterior', models.BooleanField(default=False)),
                ('num_voices', models.IntegerField(default=1)),
                ('num_musicians', models.IntegerField(default=1)),
                ('dress_code', models.CharField(blank=True, choices=[('Formal-Casual', 'Formal-Casual'), ('Formal', 'Formal'), ('Gala', 'Gala')], max_length=50, null=True, verbose_name='Código de Vestimenta')),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('contact_method', models.CharField(blank=True, choices=[('WhatsApp', 'WhatsApp'), ('Llamada Telefónica', 'Llamada Telefónica'), ('Correo Electrónico', 'Correo Electrónico')], max_length=50, null=True, verbose_name='Método de Contacto')),
                ('comments', models.TextField(blank=True, null=True)),
                ('cost_musicians_base', models.FloatField(default=0)),
                ('cost_weekend_fee', models.FloatField(default=0)),
                ('cost_distance_fee', models.FloatField(default=0)),
                ('cost_gala_fee', models.FloatField(default=0)),
                ('cost_primetime_fee', models.FloatField(default=0)),
                ('cost_manager_base', models.FloatField(default=0)),
                ('cost_manager_per_person', models.FloatField(default=0)),
                ('cost_manager_exterior', models.FloatField(default=0)),
                ('cost_manager_boda', models.FloatField(default=0)),
                ('cost_car_fee', models.FloatField(default=0)),
                ('total_musician_payout_rounded', models.FloatField(default=0)),
                ('payment_per_musician', models.FloatField(default=0, help_text='Pago individual por músico, calculado por el sistema.')),
                ('discount', models.FloatField(default=0, verbose_name='Descuento (cantidad fija)')),
                ('paid_amount', models.FloatField(default=0, verbose_name='Monto Pagado')),
                ('total_cost', models.FloatField(default=0)),
                ('calculation_log', models.TextField(blank=True, editable=False, null=True, verbose_name='Registro de Cálculo')),
                ('status', models.CharField(choices=[('UNCONFIRMED', 'Unconfirmed'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='UNCONFIRMED', max_length=20)),
                ('created_by_source', models.CharField(choices=[('WEBSITE', 'Website'), ('ADMIN', 'Admin')], default='WEBSITE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, help_text='User who created or last saved the quote in the admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.eventtype', verbose_name='Event Type')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.package', verbose_name='Paquete Seleccionado')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(help_text="Describes the change, e.g., 'Status changed from Confirmed to Completed'.", max_length=255)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quotes.quote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
