# Generated by Django 4.2.23 on 2025-06-30 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='quotehistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Historial de Cotización', 'verbose_name_plural': 'Historial de Cotizaciones'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_by_source',
            field=models.CharField(choices=[('WEBSITE', 'Sitio Web'), ('ADMIN', 'Admin')], default='WEBSITE', max_length=20, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_by_user',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó o guardó la cotización.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.eventtype', verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('UNCONFIRMED', 'Por Confirmar'), ('CONFIRMED', 'Confirmado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], db_index=True, default='UNCONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotehistory',
            name='action',
            field=models.CharField(help_text="Describe el cambio. Ej. 'Estado cambiado de Confirmado a Completado'.", max_length=255),
        ),
    ]
