# Generated by Django 4.2.23 on 2025-06-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
    ]
