# Generated by Django 4.2.23 on 2025-07-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_options_alter_quotehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='extra_charge',
            field=models.FloatField(default=0, help_text='Cargo adicional (positivo) o descuento (negativo) para ajustar manualmente el precio final.', verbose_name='Cargo Extra / Ajuste'),
        ),
    ]
