# Generated by Django 4.2.23 on 2025-06-29 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0002_populate_event_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_singers', models.PositiveIntegerField(default=1, verbose_name='Número de Voces')),
                ('num_instrument_players', models.PositiveIntegerField(default=1, verbose_name='Número de Músicos')),
                ('is_active', models.BooleanField(default=True, help_text='Show this package as an option in the quote form.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='quote',
            name='location_details',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='has_wedding_fee',
            field=models.BooleanField(default=False, help_text='Does this event type have the special wedding manager fee?'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='is_funeral_type',
            field=models.BooleanField(default=False, help_text='Does this event type (e.g., funeral) always use the weekday musician rate?'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='manager_base_fee',
            field=models.FloatField(default=200.0, help_text='The base fee for the manager for this type of event.'),
        ),
        migrations.AddField(
            model_name='program',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Descuento (cantidad fija)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='event_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Dirección del Evento'),
        ),
        migrations.AddField(
            model_name='quote',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='Monto Pagado'),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_per_musician',
            field=models.FloatField(default=0, help_text='Pago individual por músico, calculado por el sistema.'),
        ),
        migrations.CreateModel(
            name='QuoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(help_text="Describes the change, e.g., 'Status changed from Confirmed to Completed'.", max_length=255)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quotes.quote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.package', verbose_name='Paquete Seleccionado'),
        ),
    ]
