# Generated by Django 4.2.23 on 2025-06-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_package_remove_quote_location_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='quote',
            name='dress_code',
            field=models.CharField(blank=True, choices=[('Formal-Casual', 'Formal-Casual'), ('Formal', 'Formal'), ('Gala', 'Gala')], max_length=50, null=True, verbose_name='Código de Vestimenta'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='location_type',
            field=models.CharField(blank=True, choices=[('dentro_periferico', 'Dentro del periférico de Guadalajara'), ('fuera_periferico', 'Fuera del periférico (ZMG)'), ('1_hora', 'A 1 hora de Guadalajara'), ('2_horas', 'A 2 horas de Guadalajara'), ('3_horas', 'A más de 3 horas de Guadalajara')], max_length=100, null=True, verbose_name='Ubicación'),
        ),
    ]
