# Generated by Django 4.2.23 on 2025-07-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_extra_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotehistory',
            name='details',
            field=models.TextField(blank=True, help_text='JSON-formatted string of changed data.', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_car_fee',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_distance_fee',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_gala_fee',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_manager_base',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_manager_boda',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_manager_exterior',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_manager_per_person',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_musicians_base',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_primetime_fee',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost_weekend_fee',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Evento'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del Evento'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='is_exterior',
            field=models.BooleanField(default=False, verbose_name='¿Es en exterior?'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='num_musicians',
            field=models.IntegerField(default=1, help_text='Solo aplica si no se selecciona un paquete.', verbose_name='Número de Músicos'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='num_voices',
            field=models.IntegerField(default=1, help_text='Solo aplica si no se selecciona un paquete.', verbose_name='Número de Voces'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='payment_per_musician',
            field=models.FloatField(default=0, editable=False, help_text='Pago individual por músico, calculado por el sistema.'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_cost',
            field=models.FloatField(default=0, verbose_name='Costo Total (calculado)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_musician_payout_rounded',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
