# Generated by Django 4.2.23 on 2025-07-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_templates', '0001_initial'),
        ('quotes', '0004_quotehistory_details_alter_quote_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='program_template',
            field=models.ForeignKey(blank=True, help_text='Seleccione una plantilla para crear un programa para este evento. Se creará al guardar.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_templates.programtemplate', verbose_name='Plantilla de Programa'),
        ),
    ]
