# Generated by Django 4.2.23 on 2025-06-30 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_program_options_alter_quote_dress_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which to display packages on the website.'),
        ),
        migrations.AddField(
            model_name='quote',
            name='calculation_log',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Registro de Cálculo'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='quotes.program'),
        ),
    ]
