# Generated by Django 4.2.23 on 2025-06-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_package_options_package_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='quote',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, unique=True),
        ),
    ]
