# Generated by Django 4.2.23 on 2025-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_program_options_alter_quote_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('WhatsApp', 'WhatsApp'), ('Llamada Telefónica', 'Llamada Telefónica'), ('Correo Electrónico', 'Correo Electrónico')], max_length=50, null=True, verbose_name='Método de Contacto'),
        ),
    ]
